etcd:
  url: http://localhost:2479
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: monitor-managers
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.rackspace.salus.telemetry.messaging
  jackson:
    mapper:
      default-view-inclusion: true
  http:
    log-request-details: true
logging:
  level:
    web: debug
