salus:
  environment: local
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}-${salus.environment}
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.rackspace.salus.telemetry.messaging
  jackson:
    mapper:
      default-view-inclusion: true
  application:
    name: salus-telemetry-monitor-management
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}