salus:
  environment: local
  test-monitor:
    results-timeout: 60s
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}-${salus.environment}
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.rackspace.salus.telemetry.messaging
  jackson:
    mapper:
      default-view-inclusion: true
  application:
    name: salus-telemetry-monitor-management
  mvc:
    async:
      # async request timeout should be set to some duration larger than salus.test-monitor.results-timeout
      request-timeout: 70s