server:
  port: 8089
salus:
  etcd:
    url: http://localhost:2479
  services:
    resourceManagementUrl:
      http://localhost:8085
    policyManagementUrl:
      http://localhost:8091
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        generate_statistics: false
    show-sql: true
  datasource:
    username: dev
    password: pass
    url: jdbc:mysql://localhost:3306/default?verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
logging:
  level:
    com.rackspace.salus: debug
    web: debug
